export const businessUnits = [
  "architecture",
  "real_estate",
  "painting",
  "interiors",
  "tech",
  "customer_care",
] as const;
export const intents = [
  "greeting",
  "thanks",
  "language",
  "service",
  "packages",
  "design_search",
  "property_search",
  "order_status",
  "support_status",
  "payment",
  "customisation",
  "quotation",
  "viewing",
  "callback",
  "complaint",
  "contact",
  "hours",
  "professional",
  "unknown",
] as const;
